Added pwm. Closed #10.
Vladimir-ai/ESTC-project pull request #13
Opened 2021-11-14 15:39 UTC by Vladimir-ai

2021-11-15 13:14 UTC, Diadlo requested changes

2021-11-15 13:14 UTC, Diadlo commented on main.c
> +#define FULL_PERIOD                     200U
Лучше тоже добавить суффикс с размерностью. А то чего 200 не понятно

2021-11-15 13:14 UTC, Diadlo commented on main.c
> +            pwm_process_one_period(led_idx, current_cycle > 100 ? 200U - current_cycle : current_cycle);
Кажется тут должен был быть `FULL_PERIOD`. Иначе он совсем не используется

2021-11-15 13:14 UTC, Diadlo commented on pwm_module/pwm_module.c
> +  nrfx_systick_delay_us(PWM_PERCENT_TIME_US * duty_cycle);
Если есть свободное время, подумайте, можно ли сделать без delay. Т.е. надо написать функцию так, чтобы она проверяла через systick сколько времени прошло и меняло состояние только если прошло достаточно времени

2021-11-15 13:21 UTC, Vladimir-ai commented on pwm_module/pwm_module.c
> +  nrfx_systick_delay_us(PWM_PERCENT_TIME_US * duty_cycle);
Имеется ввиду при помощи nrfx_systick_test? В таком случае, что-то похожее и так реализовано внутри nrfx_systick_delay_us.

2021-11-15 13:37 UTC, Diadlo commented on pwm_module/pwm_module.c
> +  nrfx_systick_delay_us(PWM_PERCENT_TIME_US * duty_cycle);
Да с помощью `nrfx_systick_test`. В отличии от `nrfx_systick_delay_us` вам не надо "зависать" в этой функции. Если условие не наступило, то выходим из функции и так до тех пор, пока не пройдет нужное время

2021-11-15 13:40 UTC, Diadlo commented on main.c
> +            switch (current_cycle)
На счет switch тут. Я бы сказал, что switch хорош для различных перечислений. Когда мы перебираем некоторое множество возможных вариантов. А когда нас просто интересуют два значения счетчика я бы сказал, что лучше `if {} else if {}`. Но возможно больше вкусовщина. Так что feel free to ignore

2021-11-19 09:59 UTC, Diadlo approved these changes

2021-11-19 16:01 UTC, merged