Control RGB LED color
Vladimir-ai/ESTC-project pull request #18
Opened 2021-11-22 07:02 UTC by Vladimir-ai

Long click implemented with `timer_id_en_btn_timeout` that controls button state after `BTN_DISABLE_ACTIVITY_TIMEOUT`
If button is pressed time == `BTN_LONG_CLICK_TIMEOUT`, next click won't be considered as double click.
Double click is a set of two clicks when time between two clicks less than `BTN_DOUBLE_CLICK_TIMEOUT` and greater than `BTN_DISABLE_ACTIVITY_TIMEOUT`

2021-11-22 15:03 UTC, Diadlo requested changes

2021-11-22 15:03 UTC, Diadlo commented on hsv_to_rgb_module/hsv_to_rgb.c
> +__STATIC_INLINE uint8_t update_ctr(uint16_t *const ctr, uint16_t step, uint16_t max_value, uint8_t count_down)
`__STATIC_INLINE` это директивна специфичная для компилятора. Применяйте их с оторожностью. Никогда наперед не знаешь, с какими компиляторами придется работать

2021-11-22 15:03 UTC, Diadlo commented on hsv_to_rgb_module/hsv_to_rgb.c
> +  /* Use ctr, because can't send bitfield pointer to func */
Так возможно bitfield тут просто не нужен?)

2021-11-22 15:03 UTC, Diadlo commented on main.c
> +#define BTN_LONG_CLICK_TIMEOUT (APP_TIMER_CLOCK_FREQ >> 1)       /* MUST be less than BTN_DOUBLE_CLICK_TIMEOUT */
Вместо/вместе с комментарием о том, что MUST be, можно сделать static assert, который реально эту проверку сделает в compile time

2021-11-22 15:03 UTC, Diadlo commented on main.c
> +#define BTN_DISABLE_ACTIVITY_TIMEOUT (APP_TIMER_CLOCK_FREQ / 10) /* part of sec */
Для констант с временем рекомендую в имени указывать размерность (секунды, миллисекунды и т.п.), т.к. иначе в месте использования легко допустить ошибку сравнивая переменные разной размерности

2021-11-22 15:03 UTC, Diadlo commented on main.c
> +static nrf_pwm_values_individual_t rgb_sequence_values;
Возможно вместо нескольких глобальных переменных стоит создать одну структуру

2021-11-22 15:03 UTC, Diadlo commented on main.c
> +        PWM_INDICATOR_TOP_VALUE};
Если открывающая скобка на отдельной строке, то лучше и закрывающуюся поместить на отдельной

2021-11-22 15:03 UTC, Diadlo commented on hsv_to_rgb_module/hsv_to_rgb.c
> +static void hsv_to_rgb(color_params_t *const param)
Эта функция преобразует hsv в rgb, зачем ей все параметры?
Я бы предложил выделить hsv и rgb в отдельные структуры и передавать сюда только их

2021-11-22 15:03 UTC, Diadlo commented on hsv_to_rgb_module/hsv_to_rgb.h
> +  uint16_t hue:9;
А для чего тут битовое поле? Доступ к битовому полю не выровнен и осуществляется медленно. Кроме того, как вы, наверное, заметили, по указателю вы его тоже не сможете передать. Да и в общем случае битовые поля являются implementation-specific и имеют много нюансов при использовании. Стоит хорошенько подумать при их применении.

Например
* Является ли поле знаковым или беззнаковым?
* Что произойдет при битовом сдвиге битового поля?
* Что произойдет при переполнении?

На вопросы можете не отвечать, но задумайтесь, насколько вы уверены в ответах

2021-11-22 15:03 UTC, Diadlo commented on pwm_module/pwm_config.h
> +#define NRFX_PWM_DEFAULT_CONFIG_OUT0_PIN          LED_1 | NRFX_PWM_PIN_INVERTED
Лучше добавить скобки. А то ненароком сделаете `NRFX_PWM_DEFAULT_CONFIG_OUT0_PIN & SOME_FLAG` и получите `LED_1 | NRFX_PWM_PIN_INVERTED & SOME_FLAG`. У оператора `&` приоритет выше чем у `|` и поэтому в результате у вас всегда будет `LED_1`, если `SOME_FLAG` != `NRFX_PWM_PIN_INVERTED`

2021-11-22 15:03 UTC, Diadlo commented on main.c
>  static uint8_t app_flags = 0;
С битовой маской дела лучше, чем с битовыми полями, но вопрос все тот же. Зачем тут битовая маска?
Вы учитываете, что платите прозводительностью и читаемостью за то, что сохраняете тут 3 байта?
Я не говорю, что вопрос производительности нам тут как-то особо важен, но и ведь по памяти у нас запас огромный

2021-11-22 15:17 UTC, Vladimir-ai commented on main.c
> +#define BTN_DISABLE_ACTIVITY_TIMEOUT (APP_TIMER_CLOCK_FREQ / 10) /* part of sec */
Прямо так и написать 1 / `APP_TIMER_CLOCK_FREQ` секунды?

2021-11-23 06:22 UTC, Diadlo commented on main.c
> +#define BTN_DISABLE_ACTIVITY_TIMEOUT (APP_TIMER_CLOCK_FREQ / 10) /* part of sec */
1 / freq секунды это 1 тик. В подобных ситуациях можно попробовать посмотреть доки или именя параметров, где эта константа используется. В нашем случае это `app_timer_start`. Параметр `timeout_ticks`. Собтвенно вот и суффикс)

2021-11-29 12:03 UTC, Diadlo requested changes

2021-11-29 12:03 UTC, Diadlo commented on main.c
> +  app_data.flags.fst_click_occurred = 0;
Вместо `1` и `0` лучше использовать `true` и `false` соответственно

2021-11-29 12:03 UTC, Diadlo commented on main.c
> +  pwm_indicator_config.sequence_values);
Тут стоит добавить один или несколько отступов, чтобы визуально отделить параметр от инициализации поля

2021-12-03 15:05 UTC, merged